# For a real production app we would not commit this file and would be inlcuded in gitignore
# It is kept in this so that oyu the lecturer can easily clone and run our app
# without having to create your own google maps api key
MAPS_API_KEY=AIzaSyAMzvSAt9lN8KOpYtE8S9YB0Dzpml7AsV8
